module.exports = [
  {
    name: 'Joao',
    life: 10,
    mana: 100, 
    armor: 12,
    level: 3,
    classe: 'Wizard (Necromancer)', 
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvrgFiA297S1EgUWGwJLWqTg0-P-mMSGosrw&usqp=CAU",
    attributes: {
      str: 1,
      dex: 2,
      con: 3,
      int: 4,
      wis: 3,
      cha: 1,
    },
  },
  {
    name: 'Erika',
    life: 11,
    mana: 100, 
    armor: 10,
    level: 3,
    classe: 'Sorcerer', 
    image: "https://sagegamers.com/ezoimgfmt/149658804.v2.pressablecdn.com/wp-content/uploads/2021/04/FireElf.jpg?ezimgfmt=ng%3Awebp%2Fngcb1%2Frs%3Adevice%2Frscb1-2",
    attributes: {
      str: 1,
      dex: 2,
      con: 2,
      int: 3,
      wis: 2,
      cha: 5,
    },
  },
  {
    name: 'Douglas',
    life: 16,
    mana: 100, 
    armor: 14,
    level: 3,
    classe: 'Fighter', 
    image: "http://d20pfsrd.opengamingnetwork.com/wp-content/uploads/sites/12/2017/01/kolvir_comm_by_yamao-d6uy0t8-320-2.png",
    attributes: {
      str: 5,
      dex: 3,
      con: 5,
      int: 2,
      wis: 2,
      cha: 0,
    },
  },
  {
    name: 'Renata',
    life: 15,
    mana: 100,
    armor: 16,
    level: 3,
    classe: 'Cleric',
    image: "https://sagegamers.com/ezoimgfmt/149658804.v2.pressablecdn.com/wp-content/uploads/2021/10/nata___version_2_by_tropic02_dcq809c-fullview.jpg?ezimgfmt=ng%3Awebp%2Fngcb1%2Frs%3Adevice%2Frscb1-2",
    attributes: {
      str: 3,
      dex: 2,
      con: 5,
      int: 2,
      wis: 4,
      cha: 1,
    },
  },
  {
    name: 'Rebeca',
    life: 10,
    mana: 100, 
    armor: 12,
    level: 3,
    classe: 'Ranger', 
    image: "https://jogaod20com.files.wordpress.com/2020/08/o-guardic3a3o-revisado-2018.jpeg?w=810&h=580&crop=1",
    attributes: {
      str: 1,
      dex: 2,
      con: 3,
      int: 4,
      wis: 3,
      cha: 1,
    },
  },
  {
    name: 'Tiago',
    life: 11,
    mana: 100, 
    armor: 10,
    level: 3,
    classe: 'Rouge', 
    image: "https://i.pinimg.com/236x/a0/97/ab/a097ab4bb1c2b897ac7b5165dd437a57.jpg",
    attributes: {
      str: 1,
      dex: 2,
      con: 2,
      int: 3,
      wis: 2,
      cha: 5,
    },
  },
  {
    name: 'Caio',
    life: 16,
    mana: 100, 
    armor: 14,
    level: 3,
    classe: 'Barbarian', 
    image: "https://i.pinimg.com/originals/08/69/71/086971ec519d01df20ae9cb4bf5e411d.jpg",
    attributes: {
      str: 5,
      dex: 3,
      con: 5,
      int: 2,
      wis: 2,
      cha: 0,
    },
  },
  {
    name: 'Pedro',
    life: 15,
    mana: 100,
    armor: 16,
    level: 3,
    classe: 'Bard',
    image: "https://cdna.artstation.com/p/assets/images/images/025/020/872/large/henrique-dld-bardo-2final.jpg?1584327319",
    attributes: {
      str: 3,
      dex: 2,
      con: 5,
      int: 2,
      wis: 4,
      cha: 1,
    },
  },
]